host: 0.0.0.0
name: "A voice from the Cloud"
title: "A voice from the Cloud"
permalink: /blog/:title
MY_URL: https://gianarb.it
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
highlighter: none
collections:
  my_talks:
    sort_by: lesson
    output: true
exclude:
  - package.json
  - package-lock.json
  - gemset.nix
  - default.nix
  - Makefile
  - README.md
  - node_modules
  - Gemfile*
  - vendor
